### ISSUE TITLE
Bugfix Trigger for Latex Compile

### ISSUE THREAD

**Issue by philippabele** [philippabele/developers-guide-to-linux#116]
Hey @jehov4 ,

I just merged your PR regarding to compile the latex documentation with Github Actions.

Could you double check the trigger section?

https://github.com/philippabele/developers-guide-to-linux/blob/17a01d449172032d216925201e12f2090015fa30/.github/workflows/compile-latex.yml#L2

I think that it is necessary to modify the watched directory for pullrequests, because /docs does not exist in this project

https://github.com/philippabele/developers-guide-to-linux/blob/17a01d449172032d216925201e12f2090015fa30/.github/workflows/compile-latex.yml#L7

**Comment by jehov4** [comment]
Fixed the trigger.
The Latex Action seemed to have some issues with special Unicode Characters and was interpreting the subheadings differently from my Latex Compiler, fixed that.
