### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by philippabele** [philippabele/developers-guide-to-linux#119]
Hey @jehov4 ,

the current readme.md of the project could be enriched with some general information about the project.

Please take a look at [this](https://github.com/philippabele/nursing-home-volunteer#seniorenaktivierung) comparable project and add some sections about you, the project with its purpose and how to contribute.

**Comment by jehov4** [comment]
Edited in `development` branch

**Comment by jehov4** [comment]
Rewrote the first two sections into one **About the Project** section
